
<?php

// SAVE AS config.php at root of API

return [
  'HOME_URL' => 'YOUR HOME URL',

  'JWT_SECRET' => 'YOUR JWT SECRET',

  'CLIENT_ID' => 'YOUR GOOGLE CLIENT ID',
  'CLIENT_SECRET' => 'YOUR GOOGLE SECRET',
  'REDIRECT_URI' => 'YOUR GOOGLE RETURN URI',

  'DB_SERVER_NAME' => 'YOUR SERVER NAME',
  'DB_USERNAME' => 'YOUR DB USER USERNAME',
  'DB_PASSWORD' => 'YOUR DB USER PASSWORD',
  'DB_NAME' => 'YOUR DB NAME',

  'CL_KEY' => 'YOUR CLOUDINARY KEY',
  'CL_SECRET' => 'YOUR CLOUDINARY SECRET KEY',

  'CLOUD_PRESET' => 'YOUR CLOUDINARY PRESET',
  'CLOUD_UPLOAD' => 'YOUR CLOUDINARY UPLOAD LINK',
];
